name: across

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 8000:8000
    environment:
      APP_ENV: production
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgis/postgis
    volumes:
      - across-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: local
      POSTGRES_DB: across

volumes:
  across-pg-data:
