## file: .github/configs/environment.yaml

# assumes the same organization
environment-info-org: ACROSS-Team
environment-info-repo: across-infrastructure
implementation_path: .github/environments
implementation_file: ecspresso.yaml
implementation_ref: main
