name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Formatting (Ruff)
        uses: astral-sh/ruff-action@v1
        with:
          args: format --check
          changed-files: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.34.0
          cache: true
          environments: "lint"
          activate-environment: true

      - name: Linting (Ruff)
        uses: astral-sh/ruff-action@v1
        with:
          changed-files: true

      - name: Static Analysis (mypy)
        run: |
          mypy **/*/*.py

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          build-args: |
            APP_ENV=production

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.34.0
          cache: true
          environments: "test"
          activate-environment: true

      - name: Tests
        run: pytest --cov=across_server **/*/*.py
