name: Main Branch
on:
  push:
    branches: [main]
    paths-ignore:
      # We only want to run main branch workflow on code change PRs and ignore
      # release-please PRs since they do not need another deploy to dev.
      # release-please PRs only ever get generated AFTER a successful deploy to dev.
      # release-pr _should_ be the only PR to ever modify this.
      - across_server/__init__.py
      - .release-please-manifest.json
      - CHANGELOG.md
      - release-please-config.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  deployments: write
  pull-requests: write
  contents: read

jobs:
  do:
    uses: NASA-ACROSS/github-action-workflows/.github/workflows/ecspresso-main-branch.yml@main
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      image-name: core-server
      app: core-server
      enable-migration: true
      migration-env-overrides: |
        [{ "name": "ACROSS_DB_USER", "value": "ci" }]
    secrets:
      github-private-actions-pat: "${{ secrets.PRIVATE_CONFIG_READ_ACCESS }}"
      registry: "${{ secrets.ECR_REGISTRY }}"
      secret-outputs-passphrase: "${{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE }}"
      ecr-region: "${{ secrets.ECR_REGION }}"
      ecr-iam-role: "${{ secrets.ECR_IAM_ROLE }}"
      release-please-token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
